# Generated by Django 5.1.1 on 2026-04-22 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazovVybavenia', models.CharField(max_length=100)),
                ('pocetKusov', models.IntegerField()),
                ('popis', models.CharField(max_length=500)),
                ('typVybavenia', models.CharField(choices=[('EL', 'Elektronika'), ('NA', 'Nábytok'), ('SP', 'Šport'), ('IN', 'Iné')], default='IN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazovMiestnosti', models.CharField(max_length=100)),
                ('cisloMiestnosti', models.IntegerField()),
                ('kapacitaMiestnosti', models.IntegerField()),
                ('typMiestnosti', models.CharField(choices=[('UC', 'Učebňa'), ('LA', 'Laboratórium'), ('TE', 'Telocvičňa'), ('KA', 'Kancelária'), ('KN', 'Knižnica'), ('IN', 'Iné')], default='IN', max_length=2)),
                ('popisMiestnosti', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meno', models.CharField(max_length=100)),
                ('Priezvisko', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazovRezervacie', models.CharField(max_length=100)),
                ('datumRezervacie', models.DateField()),
                ('casOd', models.TimeField()),
                ('casDo', models.TimeField()),
                ('ucelRezervacie', models.CharField(max_length=100)),
                ('miestnostRezervacie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rezervacie', to='rezervacie.room')),
                ('pouzivatelRezervacie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rezervacie', to='rezervacie.user')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('casDo__gt', models.F('casOd'))), name='casDo_must_be_after_casOd')],
            },
        ),
    ]
