# Generated by Django 5.1.1 on 2026-04-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocetKusov', models.IntegerField()),
                ('poznamka', models.CharField(max_length=100)),
                ('rezervacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervacie.reservation')),
                ('vybavenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervacie.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='vybavenie',
            field=models.ManyToManyField(through='rezervacie.ReservationEquipment', to='rezervacie.equipment'),
        ),
    ]
