# Generated by Django 5.1.1 on 2026-04-29 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacie', '0002_reservationequipment_reservation_vybavenie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pouzivatelRezervacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rezervacie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='pocetKusov',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='nazovRezervacie',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='popis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='vybavenie',
            field=models.ManyToManyField(blank=True, null=True, through='rezervacie.ReservationEquipment', to='rezervacie.equipment'),
        ),
        migrations.AlterField(
            model_name='reservationequipment',
            name='poznamka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='popisMiestnosti',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
