# Generated by Django 5.1.1 on 2026-06-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacie', '0003_alter_reservation_pouzivatelrezervacie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='vybavenie',
            field=models.ManyToManyField(blank=True, through='rezervacie.ReservationEquipment', to='rezervacie.equipment'),
        ),
    ]
